openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
- url: https://localhost:8002
  description: Generated server url
paths:
  /Logout:
    post:
      tags:
      - logout
      operationId: logout
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Response'
  /Login:
    post:
      tags:
      - login
      operationId: login
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Request'
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Response'
  /CreateUsers:
    post:
      tags:
      - create-users
      operationId: createUsers
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Request'
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Response'
  /UpdateUsers:
    patch:
      tags:
      - update-users
      operationId: updateUsers
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Request'
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Response'
  /ListUsers:
    get:
      tags:
      - list-users
      operationId: listUsers
      parameters:
      - name: request
        in: query
        required: true
        schema:
          $ref: '#/components/schemas/Request'
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Response'
  /GetRandomOutcome:
    get:
      tags:
      - get-random-outcome
      operationId: getRandomOutcome
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Response'
  /GetAuthenticatedHello:
    get:
      tags:
      - get-authenticated-hello
      operationId: getAuthenticatedHello
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Response'
  /DescribeUsers:
    get:
      tags:
      - describe-users
      operationId: describeUsers
      parameters:
      - name: request
        in: query
        required: true
        schema:
          $ref: '#/components/schemas/Request'
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Response'
  /DeleteUsers:
    delete:
      tags:
      - delete-users
      operationId: deleteUsers
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Request'
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Response'
components:
  schemas:
    Response:
      type: object
      properties:
        message:
          type: string
    Request:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
