server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: system
          __path__: /var/log/*log
  - job_name: yawa
    static_configs:
      - targets:
          - localhost
        labels:
          application: yawa
          component: server
          stack: dev
          region: local
          __path__: /var/yawa/logs/application.log
    pipeline_stages:
    - match:
        selector: '{application="yawa"}'
        stages:
        - regex:
            expression: '^(?P<timestamp>[^ ]+)\s(?P<level>[^ ]+)\s+(?P<requestId>[^ ]+)\s(?P<logger>[^ ]+)\s(?P<fileAndLine>[^ ]+)\s(?P<message>.*)$'
        - labels:
            level:
            requestId:
        - timestamp:
            format: RFC3339Nano
            source: timestamp