version: "3.9"

services:
  frontend:
    container_name: frontend
    build:
      context: frontend
    ports:
      - "8010:3000"
    env_file: frontend/docker.env
    restart: always
    volumes:
      - ./frontend:/usr/src/yawa/frontend
    stdin_open: true #https://github.com/docker/compose/issues/5016
    depends_on:
      - server

  server:
    container_name: server
    build:
      context: server
    ports:
      - "8002:8000"  # Server
      - "8006:8001"  # Debugger
      - "8008:9080"  # Promtail
    restart: always
    volumes:
      - srvdata:/var/yawa
      - ./server/.container/var/yawa:/var/yawa
      - ./server:/usr/src/yawa
    depends_on:
      - database
      - cache

  database:
    container_name: database
    build:
      context: database
    env_file: database/docker.env
    ports:
      - "3307:3306"
    restart: always
    volumes:
      - dbdata:/var/lib/mysql

  dbadmin:
    container_name: dbadmin
    image: phpmyadmin
    restart: always
    ports:
      - "8003:80"
    environment:
      - PMA_ARBITRARY=1
    depends_on:
      - database

  cache:
    container_name: cache
    build:
      context: cache
    env_file: cache/docker.env
    ports:
      - "6000:6379"
    restart: always
    volumes:
      - cachedata:/var/redis
      - ./cache/.container/var/redis/logs:/var/redis/logs

  prometheus:
    container_name: prometheus
    build:
      context: prometheus
    env_file: prometheus/docker.env
    restart: always
    ports:
      - "8004:9090"
    volumes:
      - ./prometheus/config/prometheus.yaml:/etc/prometheus/prometheus.yml
      - ./prometheus/config/secrets/yawa-credentials.txt:/etc/prometheus/yawa-credentials.txt
    depends_on:
      - server

  grafana:
    container_name: grafana
    build:
      context: grafana
    restart: always
    ports:
      - "8005:3000"
    volumes:
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/dashboards:/var/lib/grafana/dashboards
      - ./grafana/public/home.json:/usr/share/grafana/public/dashboards/home.json
    depends_on:
      - prometheus
      - loki

  loki:
    container_name: loki
    build:
      context: loki
    restart: always
    ports:
      - "8007:3100"
    volumes:
      - ./loki/config/loki.yaml:/etc/loki/local-config.yaml

volumes:
  srvdata:
  dbdata:
  cachedata:
