version: "3.9"

services:
  #frontend:
  #  container_name: frontend
  #  build:
  #    context: frontend
  #  ports:
  #    - 3000:3000
  #  env_file: frontend/docker.env
  #  restart: always
  #  stdin_open: true #https://github.com/docker/compose/issues/5016
  #  depends_on:
  #    - database
  #    - server

  server-node:
    container_name: server-node
    build:
      context: server-node
    ports:
      - 8001:8000
    env_file: server-node/docker.env
    restart: always
    volumes:
      - ./server-node:/usr/src/yawa
      - /usr/src/yawa/node_modules
      - ./server-node/.container/var/yawa/logs:/var/yawa/logs
    depends_on:
      - database

  server-spring:
    container_name: server-spring
    build:
      context: server-spring
    ports:
      - 8002:8000
    env_file: server-spring/docker.env
    restart: always
    volumes:
      - ./server-spring:/usr/src/yawa
      - ./server-spring/.container/var/yawa/logs:/var/yawa/logs
    depends_on:
      - database

  database:
    container_name: database
    build:
      context: database
    env_file: database/docker.env
    ports:
      - 3307:3306
    restart: always
    volumes:
      - dbdata:/var/lib/mysql

  dbadmin:
    container_name: dbadmin
    image: phpmyadmin
    restart: always
    ports:
      - 8081:80
    environment:
      - PMA_ARBITRARY=1
    depends_on:
      - database

volumes:
  dbdata: