yawa:
  application: yawa
  service: server
  stack: stack
  region: region
  filesystem:
    rootDir: "/var/yawa"
#  security:
#    jwt:
#      secret: FROM classpath:secrets/application.yaml
  cache:
    host: cache-host
    port: 1234
#    username: FROM classpath:secrets/application.yaml
#    password: FROM classpath:secrets/application.yaml
server:
  port: 8000
  ssl:
    enabled: true
    key-store: classpath:secrets/certificates/YAWA.p12
    key-store-type: pkcs12
  #    key-alias: FROM classpath:secrets/application.yaml
#    key-store-password: FROM classpath:secrets/application.yaml
#    key-password: FROM classpath:secrets/application.yaml
  error:
    include-message: always
    include-stacktrace: never
    include-exception: false
    include-binding-errors: never
    whitelabel:
      enabled: false
  shutdown: graceful
spring:
  config:
    import: classpath:secrets/application.yaml
  profiles:
    default: docker
  jpa:
    database: mysql
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  datasource:
    url: jdbc:mysql://database:3306/dbyawa?useSSL=false&allowPublicKeyRetrieval=true
#   username: FROM classpath:secrets/application.yaml
#   password: FROM classpath:secrets/application.yaml
  output:
    ansi:
      enabled: detect
  mustache:
    check-template-location: false
  pid:
    file: /var/yawa/run/yawa.pid
    fail-on-write-error: true
  lifecycle:
    timeout-per-shutdown-phase: 60s
#  security:
#    oauth2:
#      client:
#        registration:
#          google:
#            client-id: FROM classpath:secrets/application.yaml
#            client-secret: FROM classpath:secrets/application.yaml
  mail:
    host: smtp.gmail.com
    port: 587
#    username: FROM classpath:secrets/application.yaml
#    password: FROM classpath:secrets/application.yaml
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp
    test-connection: false
logging:
  config: classpath:logging/logback.xml
management:
  endpoints:
    enabled-by-default: false
    web:
      base-path: /manage
      exposure:
        include: configprops,env,health,info,mappings,metrics,openapi,prometheus,shutdown,swagger-ui
  endpoint:
    configprops:
      enabled: true
    env:
      enabled: true
    health:
      show-components: always
      show-details: always
      enabled: true
    info:
      enabled: true
    mappings:
      enabled: true
    metrics:
      enabled: true
    prometheus:
      enabled: true
    shutdown:
      enabled: true
  health:
    custom:
      enabled: true
    db:
      enabled: true
    diskspace:
      enabled: true
    ping:
      enabled: true
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  info:
    build:
      enabled: true
    git:
      enabled: true
      mode: full
    java:
      enabled: true
    os:
      enabled: true
    custom:
      enabled: false
    defaults:
      enabled: false
  metrics:
    web:
      server:
        request:
          autotime:
            enabled: true
springdoc:
  api-docs:
    enabled: true
    path: /docs/openapi
  swagger-ui:
    enabled: true
    path: /docs/swagger-ui.html
  show-actuator: true
