yawa:
  application: yawa
  service: server
  stack: stack
  region: region
server:
  port: 8000
  ssl:
    enabled: true
    key-store: classpath:certificates/yawa.keystore
    key-store-type: pkcs12
    key-alias: yawa
    key-store-password: yawapass
    key-password: yawapass
  error:
    include-message: always
    include-stacktrace: never
    include-exception: false
    include-binding-errors: never
    whitelabel:
      enabled: false
  shutdown: graceful
spring:
  profiles:
    default: docker
  jpa:
    database: mysql
    show-sql: false
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:mysql://database:3306/dbyawa?useSSL=false
    username: dbuser
    password: dbpassword
  output:
    ansi:
      enabled: detect
  mustache:
    check-template-location: false
  pid:
    file: /var/yawa/run/yawa.pid
    fail-on-write-error: true
  lifecycle:
    timeout-per-shutdown-phase: 60s
#  security:
#    oauth2:
#      client:
#        registration:
#          google:
#            client-id: "31171094515-jdf9rm9820bin2q38lcisbs5k1mt7c4g.apps.googleusercontent.com"
#            client-secret: "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"
logging:
  config: classpath:logging/logback.xml
management:
  endpoints:
    enabled-by-default: false
    web:
      base-path: /manage
      exposure:
        include: configprops,env,health,info,mappings,metrics,prometheus,shutdown
  endpoint:
    configprops:
      enabled: true
    env:
      enabled: true
    health:
      show-components: always
      show-details: always
      enabled: true
    info:
      enabled: true
    mappings:
      enabled: true
    metrics:
      enabled: true
    prometheus:
      enabled: true
    shutdown:
      enabled: true
  health:
    custom:
      enabled: true
    db:
      enabled: true
    diskspace:
      enabled: true
    ping:
      enabled: true
  info:
    build:
      enabled: true
    git:
      enabled: true
      mode: full
    java:
      enabled: true
    os:
      enabled: true
    defaults:
      enabled: false
  metrics:
    web:
      server:
        request:
          autotime:
            enabled: true
springdoc:
  api-docs:
    path: /manage/openapi
  swagger-ui:
    path: /manage/swagger-ui
  show-actuator: true
  default-consumes-media-type: "application/json"
  default-produces-media-type: "application/json"
