yawa:
  stack: dev
  region: local
  filesystem:
    rootDir: .local/var/yawa
  cache:
    host: localhost
    port: 6000
spring:
  config:
    activate:
      on-profile: local
  devtools:
    restart:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://127.0.0.1:3307/dbyawa?useSSL=false&allowPublicKeyRetrieval=true
  pid:
    file: .local/yawa.pid
server:
  error:
    include-message: always
    include-stacktrace: always
    include-exception: true
    include-binding-errors: always
    whitelabel:
      enabled: false
