global:
  scrape_interval: 10s
scrape_configs:
  - job_name: prometheus
    scrape_interval: 5s
    scheme: http
    static_configs:
      - targets: [ 'localhost:9090' ]
  - job_name: spring-micrometer
    metrics_path: /manage/prometheus
    scrape_interval: 5s
    scheme: https
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets: ['server:8000']