apiVersion: 1

deleteDatasources:
  - name: YAWA-Prometheus
    orgId: 1
  - name: YAWA-Loki
    orgId: 1

datasources:
 - name: YAWA-Prometheus
   type: prometheus
   access: proxy
   orgId: 1
   url: http://prometheus:9090
   isDefault: true
   jsonData:
     tlsSkipVerify: true
     httpMethod: GET
   editable: false
   version: 1
 - name: YAWA-Loki
   type: loki
   orgId: 1
   url: http://loki:3100
   editable: false
   version: 1
