apiVersion: 1

deleteDatasources:
  - name: YAWA
    orgId: 1

datasources:
 - name: YAWA
   type: prometheus
   access: proxy
   orgId: 1
   url: http://prometheus:9090
   isDefault: true
   jsonData:
     tlsSkipVerify: true
     httpMethod: GET
   editable: false
   version: 1