{
 "title": "YAWA API",
 "description": "Dashboard for YAWA API monitoring",
 "tags": [
  "yawa",
  "api"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "application", "label": "Application", "query": "yawa" },
   { "name": "service", "label": "Service", "query": "server" },
   {
    "name": "stack",
    "label": "Stack",
    "query": {
     "query": "label_values(http_server_requests_seconds_count{application=\"$application\", service=\"$service\"}, stack)"
    }
   },
   {
    "name": "region",
    "label": "Region",
    "query": {
     "query": "label_values(http_server_requests_seconds_count{application=\"$application\", service=\"$service\", stack=\"$stack\"}, region)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(http_server_requests_seconds_count{application=\"$application\", service=\"$service\", stack=\"$stack\", region=\"$region\"}, instance)"
    }
   },
   {
    "name": "operation",
    "label": "Operation",
    "query": {
     "query": "label_values(http_server_requests_seconds_count{application=\"$application\", service=\"$service\", stack=\"$stack\", region=\"$region\", instance=\"$instance\"}, operation)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Availability",
   "type": "stat",
   "description": "Availability -- 1h",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{application=\"$application\", stack=\"$stack\", region=\"$region\", operation=\"$operation\", outcome=\"SUCCESS\"}[1h])) / sum(rate(http_server_requests_seconds_count{application=\"$application\", stack=\"$stack\", region=\"$region\", operation=\"$operation\"}[1h]))"
    }
   ]
  },
  {
   "title": "Volume",
   "type": "stat",
   "description": "Per-second requests -- 1h",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{application=\"$application\", stack=\"$stack\", region=\"$region\", operation=\"$operation\"}[1h])*3600)"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "stat",
   "description": "Latency -- 1h",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_sum{application=\"$application\", stack=\"$stack\", region=\"$region\", operation=\"$operation\"}[1h])) / sum(rate(http_server_requests_seconds_count{application=\"$application\", stack=\"$stack\", region=\"$region\", operation=\"$operation\"}[1h]))"
    }
   ]
  },
  {
   "title": "Availability",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{application=\"$application\", stack=\"$stack\", region=\"$region\", operation=\"$operation\", outcome=\"SUCCESS\"}[1m])) / sum(increase(http_server_requests_seconds_count{application=\"$application\", stack=\"$stack\", region=\"$region\", operation=\"$operation\"}[1m]))",
     "legendFormat": "Availability"
    }
   ]
  },
  {
   "title": "Volume",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{application=\"$application\", stack=\"$stack\", region=\"$region\", operation=\"$operation\"}[1m])*60)",
     "legendFormat": "Requests"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_sum{application=\"$application\", stack=\"$stack\", region=\"$region\", operation=\"$operation\"}[1m])) / sum(rate(http_server_requests_seconds_count{application=\"$application\", stack=\"$stack\", region=\"$region\", operation=\"$operation\"}[1m]))",
     "legendFormat": "Latency"
    }
   ]
  },
  {
   "title": "Volume",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{application=\"$application\", stack=\"$stack\", region=\"$region\", operation=\"$operation\"}[1m])*60)",
     "legendFormat": "ALL"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_count{application=\"$application\", stack=\"$stack\", region=\"$region\", operation=\"$operation\", outcome=\"SUCCESS\"}[$__rate_interval]))",
     "legendFormat": "SUCCESS"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_count{application=\"$application\", stack=\"$stack\", region=\"$region\", operation=\"$operation\", outcome=\"SERVER_ERROR\"}[$__rate_interval]))",
     "legendFormat": "SERVER_ERROR"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_count{application=\"$application\", stack=\"$stack\", region=\"$region\", operation=\"$operation\", outcome=\"CLIENT_ERROR\"}[$__rate_interval]))",
     "legendFormat": "CLIENT_ERROR"
    }
   ]
  },
  {
   "title": "Server Errors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{application=\"$application\", stack=\"$stack\", region=\"$region\", operation=\"$operation\", outcome=\"SERVER_ERROR\"}[1m])*60) ",
     "legendFormat": "ALL"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_count{application=\"$application\", stack=\"$stack\", region=\"$region\", operation=\"$operation\", outcome=\"SERVER_ERROR\"}[$__rate_interval])) by(exception)",
     "legendFormat": "{{exception}}"
    }
   ]
  },
  {
   "title": "Client Errors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{application=\"$application\", stack=\"$stack\", region=\"$region\", operation=\"$operation\", outcome=\"CLIENT_ERROR\"}[1m])*60)",
     "legendFormat": "ALL"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_count{application=\"$application\", stack=\"$stack\", region=\"$region\", operation=\"$operation\", outcome=\"CLIENT_ERROR\"}[$__rate_interval])) by(exception)",
     "legendFormat": "{{exception}}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_sum{application=\"$application\", stack=\"$stack\", region=\"$region\", operation=\"$operation\"}[1m])) / sum(rate(http_server_requests_seconds_count{application=\"$application\", stack=\"$stack\", region=\"$region\", method=\"$method\", uri=\"$uri\"}[1m]))",
     "legendFormat": "ALL"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_sum{application=\"$application\", stack=\"$stack\", region=\"$region\", operation=\"$operation\", outcome=\"SUCCESS\"}[$__rate_interval])) / sum(rate(http_server_requests_seconds_count{application=\"$application\", stack=\"$stack\", region=\"$region\", operation=\"$operation\", outcome=\"SUCCESS\"}[$__rate_interval]))",
     "legendFormat": "SUCCESS"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_sum{application=\"$application\", stack=\"$stack\", region=\"$region\", operation=\"$operation\", outcome=\"SERVER_ERROR\"}[$__rate_interval])) / sum(rate(http_server_requests_seconds_count{application=\"$application\", stack=\"$stack\", region=\"$region\", operation=\"$operation\", outcome=\"SERVER_ERROR\"}[$__rate_interval]))",
     "legendFormat": "SERVER_ERROR"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_sum{application=\"$application\", stack=\"$stack\", region=\"$region\", operation=\"$operation\", outcome=\"CLIENT_ERROR\"}[$__rate_interval])) / sum(rate(http_server_requests_seconds_count{application=\"$application\", stack=\"$stack\", region=\"$region\", operation=\"$operation\", outcome=\"CLIENT_ERROR\"}[$__rate_interval]))",
     "legendFormat": "CLIENT_ERROR"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "logs",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 38 },
   "targets": [
    {
     "expr": "{application=\"$application\", stack=\"$stack\", region=\"$region\", service=\"$service\"} | json | logger_name = \"com.yawa.server.interceptors.AccessLogger\" | operation = \"$operation\" | message =~ \".*REQUEST END.*\" | line_format \"{{._timestamp}} {{.requestId}} {{.message}}\"",
     "maxLines": 100
    }
   ]
  }
 ]
}