global:
  scrape_interval: 5s
scrape_configs:
  - job_name: yawa-server
    metrics_path: /manage/prometheus
    scheme: https
    tls_config:
      insecure_skip_verify: true
    authorization:
      type: Bearer
      credentials: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6ImFkbWluIn0.e3UwvG12weaHaVWZ2u-vuH1SkOb6Ee0NFMVJGtTgwio
    static_configs:
      - targets: ['server:8000']
