global:
  scrape_interval: 5s
scrape_configs:
  - job_name: yawa-server
    metrics_path: /manage/prometheus
    scheme: https
    tls_config:
      insecure_skip_verify: true
    authorization:
      type: Bearer
      credentials_file: /etc/prometheus/yawa-credentials.txt
    static_configs:
      - targets: ['server:8000']
