global:
  scrape_interval: 5s
scrape_configs:
  - job_name: yawa-server
    metrics_path: /manage/prometheus
    scheme: https
    tls_config:
      insecure_skip_verify: true
    authorization:
      type: Bearer
      credentials: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6InByb21ldGhldXMifQ.Z_4lE37inXUhS8YpaYYzlmy56yjxesxlkLKpxnWc4iM
    static_configs:
      - targets: ['server:8000']
