#!/usr/bin/env bash
set -ex

PROJECT_PATH="$(realpath "$( cd -- "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )/..")"

JAVA_VERSION="17.0.9-amzn"

# Gradle 7.6.0 is the maximum version supported by the Kotlin Gradle Plugin.
# If you are considering to upgrade Gradle, you first need to check the compatibility.
# See https://kotlinlang.org/docs/gradle-configure-project.html#check-for-jvm-target-compatibility-of-related-compile-tasks
GRADLE_VERSION="7.6"

# Python is used for YAWA Ops tools
PYTHON_VERSION="3.12.0"
PYTHON_VENV="yawa-ops-dev"

# Install SDKMAN; see https://sdkman.io/install
curl -s "https://get.sdkman.io" | bash
source "$HOME/.sdkman/bin/sdkman-init.sh"

# Install Java and set as default version
sdk install java $JAVA_VERSION
sdk default java $JAVA_VERSION

# Install Gradle and set as default version
sdk install gradle $GRADLE_VERSION
sdk default gradle $GRADLE_VERSION

brew install docker docker-compose # Docker environment
brew install openapi-generator # OpenAPI generator
brew install mysql # MySQL client
brew install bash # Bash clients generated by OpenAPI require Bash >=5
brew install bash-completion # Bash completion used by generated clients
brew install jq # Required by some of our scripts
brew install ktlint # Kotlin linter
brew install pyenv # Python Virtual Environments

# Install Pre-Commit, which is required to contribute to the repository
brew install pre-commit
pre-commit install

# Create Python Virtual Environment for YAWA Ops
pyenv install $PYTHON_VERSION --skip-existing
pyenv virtualenv $PYTHON_VERSION $PYTHON_VENV --force
echo "$PYTHON_VENV" > "$PROJECT_PATH/ops/.python-version"
"$(pyenv virtualenv-prefix $PYTHON_VENV)/envs/$PYTHON_VENV/bin/python" -m pip install --upgrade pip
"$(pyenv virtualenv-prefix $PYTHON_VENV)/envs/$PYTHON_VENV/bin/python" -m pip install -e "$PROJECT_PATH/ops"
