#!/usr/bin/env bash
set -e

PROJECT_PATH="$(realpath "$( cd -- "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )/..")"

source "${PROJECT_PATH}/tools/common.sh"

JAVA_VERSION="17.0.9-amzn"

# Gradle 7.6.0 is the maximum version supported by the Kotlin Gradle Plugin.
# If you are considering to upgrade Gradle, you first need to check the compatibility.
# See https://kotlinlang.org/docs/gradle-configure-project.html#check-for-jvm-target-compatibility-of-related-compile-tasks
GRADLE_VERSION="8.10.2"

# Python is used for YAWA Ops tools
PYTHON_VERSION="3.12.8"
PYTHON_VENV="yawa-ops-dev"

NVM_VERSION="0.40.2"
NODE_VERSION="20.19.0"

info "Installing SDKMAN"
curl -s "https://get.sdkman.io" | bash
source "$HOME/.sdkman/bin/sdkman-init.sh"

info "Installing Java"
sdk install java $JAVA_VERSION
sdk default java $JAVA_VERSION

info "Installing Gradle"
sdk install gradle $GRADLE_VERSION
sdk default gradle $GRADLE_VERSION

info "Installing tools"
brew install docker docker-compose # Docker environment
brew install openapi-generator # OpenAPI generator
brew install mysql # MySQL client
brew install bash # Bash clients generated by OpenAPI require Bash >=5
brew install bash-completion # Bash completion used by generated clients
brew install jq # Required by some of our scripts
brew install ktlint # Kotlin linter
brew install pyenv # Python Virtual Environments

info "Installing pre-commit"
brew install pre-commit
pre-commit install

info "Creating Python virtual environment for yawa-ops"
pyenv install $PYTHON_VERSION --skip-existing
pyenv virtualenv $PYTHON_VERSION $PYTHON_VENV --force
echo "$PYTHON_VENV" > "$PROJECT_PATH/ops/.python-version"
"$(pyenv virtualenv-prefix $PYTHON_VENV)/envs/$PYTHON_VENV/bin/python" -m pip install --upgrade pip

info "Installing NVM"
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v${NVM_VERSION}/install.sh | bash
export NVM_DIR="${HOME}/.nvm"
[ -s "${NVM_DIR}/nvm.sh" ] && \. "${NVM_DIR}/nvm.sh"  # This loads nvm
[ -s "${NVM_DIR}/bash_completion" ] && \. "${NVM_DIR}/bash_completion"  # This loads nvm bash_completion

info "Installing Node.js and fronted dependencies"
nvm install ${NODE_VERSION}
npm install --global npm
npm install --global yarn
npm install --global gulp-cli
pushd  "${PROJECT_PATH}/frontend"
yarn install
popd

warn "TODO Setting up certificates"

info "Your dev environment is ready! Now reload your shell"
