name: Docker Build

on:
  push:
    branches: [ "mainline" ]
  pull_request:
    branches: [ "mainline" ]

jobs:
  docker-build:
    name: Docker build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ "ubuntu-20.04" ]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0
      - name: Setup Docker
        uses: docker-practice/actions-setup-docker@master
        timeout-minutes: 10
      - name: Start Containers
        run: docker-compose up --detach --build
        timeout-minutes: 5
      - name: Stop Containers
        run: docker-compose down
        timeout-minutes: 2
