name: Docker Build

on:
  push:
    branches: [ "mainline" ]
  pull_request:
    branches: [ "mainline" ]

jobs:
  docker-build:
    name: Docker build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ "ubuntu-20.04" ]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      - name: Docker Compose Action
        uses: isbang/compose-action@v1.4.1
        with:
          compose-file: docker-compose.yaml
#
#      - name: Install Docker Compose
#        run: sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
#
#      - name: Make Docker Compose Executable
#        run: sudo chmod +x /usr/local/bin/docker-compose
#
#      - name: Build
#        run: docker-compose build
